/**
 * Italien-Roadtrip 2026 — Seed-Daten (read-only Quelle)
 */
const TRIP_DATA = {
  meta: {
    title: 'Italien-Roadtrip 2026',
    subtitle: 'Luxemburg → Bari (Hochzeit) → Italien → Luxemburg',
    start: '2026-07-27',
    end: '2026-08-08',
    origin: 'Luxemburg',
    hotelBudgetTarget: 1940,
    hotelPicksTotal: 1926,
    restaurantBudgetEstimate: { min: 300, max: 500 },
    tollsEstimate: { min: 110, max: 150 },
    fuelEstimate: { min: 200, max: 280 },
    totalDriveKm: 4155,
    adults: 2,
  },

  routeStops: [
    { id: 'lux', label: 'Luxemburg', dayId: null, segment: 'start', lat: 49.6116, lng: 6.1319 },
    { id: 'innsbruck', label: 'Innsbruck', dayId: 'day-1', segment: 'outbound', lat: 47.2692, lng: 11.4041 },
    { id: 'pesaro', label: 'Pesaro', dayId: 'day-2', segment: 'outbound', lat: 43.9097, lng: 12.9133 },
    { id: 'bari', label: 'Bari', dayId: 'day-3', segment: 'wedding', lat: 41.1171, lng: 16.8719 },
    { id: 'matera', label: 'Matera', dayId: 'day-5', segment: 'italy', lat: 40.6664, lng: 16.6043 },
    { id: 'rome', label: 'Rom', dayId: 'day-6', segment: 'italy', lat: 41.9028, lng: 12.4964 },
    { id: 'siena', label: 'Siena', dayId: 'day-8', segment: 'italy', lat: 43.3188, lng: 11.3308 },
    { id: 'bologna', label: 'Bologna', dayId: 'day-10', segment: 'italy', lat: 44.4949, lng: 11.3426 },
    { id: 'stresa', label: 'Stresa', dayId: 'day-11', segment: 'italy', lat: 45.8842, lng: 8.5298 },
    { id: 'lux-end', label: 'Luxemburg', dayId: 'day-13', segment: 'return', lat: 49.6116, lng: 6.1319 },
  ],

  placeCoords: {
    Innsbruck: { lat: 47.2692, lng: 11.4041 },
    Pesaro: { lat: 43.9097, lng: 12.9133 },
    Bari: { lat: 41.1171, lng: 16.8719 },
    Matera: { lat: 40.6664, lng: 16.6043 },
    Rom: { lat: 41.9028, lng: 12.4964 },
    Siena: { lat: 43.3188, lng: 11.3308 },
    Bologna: { lat: 44.4949, lng: 11.3426 },
    Modena: { lat: 44.6471, lng: 10.9252 },
    Stresa: { lat: 45.8842, lng: 8.5298 },
    'Lake Orta (von Stresa)': { lat: 45.7936, lng: 8.4103 },
    Mergozzo: { lat: 45.9411, lng: 8.4562 },
    "Colle Val d'Elsa": { lat: 43.4217, lng: 11.1267 },
    Montalcino: { lat: 43.0578, lng: 11.4889 },
  },

  statusOptions: {
    booking: [
      { value: 'offen', label: 'Offen' },
      { value: 'recherchiert', label: 'Recherchiert' },
      { value: 'gebucht', label: 'Gebucht' },
      { value: 'bestaetigt', label: 'Bestätigt' },
    ],
  },

  days: [
    {
      id: 'day-1',
      date: '2026-07-27',
      weekday: 'Mo',
      label: 'Tag 1',
      route: 'Luxemburg → Innsbruck',
      km: 720,
      hours: 7,
      sleep: 'Innsbruck',
      hotelId: 'hotel-innsbruck',
      segment: 'Transit nach Bari',
      type: 'overnight',
      ztlLevel: null,
      activities: ['Optional: Abendspaziergang Altstadt (Goldenes Dachl)', 'Tyroler Abendessen'],
    },
    {
      id: 'day-2',
      date: '2026-07-28',
      weekday: 'Di',
      label: 'Tag 2',
      route: 'Innsbruck → Brenner → Pesaro',
      km: 700,
      hours: 7,
      sleep: 'Pesaro',
      hotelId: 'hotel-pesaro',
      segment: 'Transit nach Bari',
      type: 'overnight',
      ztlLevel: 'low',
      activities: ['Sonnenuntergang Lungomare', 'Fisch-Abendessen am Strand'],
    },
    {
      id: 'day-3',
      date: '2026-07-29',
      weekday: 'Mi',
      label: 'Tag 3',
      route: 'Pesaro → Bari',
      km: 530,
      hours: 5.5,
      sleep: 'Bari (gebucht)',
      hotelId: 'hotel-bari',
      segment: 'Transit / Hochzeit',
      type: 'booked',
      ztlLevel: null,
      activities: ['Ankunft Nachmittag, einchecken'],
    },
    {
      id: 'day-4',
      date: '2026-07-30',
      weekday: 'Do',
      label: 'Tag 4',
      route: '—',
      km: 0,
      hours: 0,
      sleep: 'Bari (gebucht)',
      hotelId: 'hotel-bari',
      segment: 'Hochzeit',
      type: 'wedding',
      ztlLevel: null,
      activities: ['Hochzeit'],
    },
    {
      id: 'day-5',
      date: '2026-07-31',
      weekday: 'Fr',
      label: 'Tag 5',
      route: 'Bari → Matera',
      km: 65,
      hours: 1,
      sleep: 'Matera',
      hotelId: 'hotel-matera',
      segment: 'Italien nach Bari',
      type: 'explore',
      ztlLevel: 'pedestrian',
      activities: [
        'Sassi bei golden hour',
        'Geführter Walk Sasso Caveoso',
        'Abendessen Vitantonio Lombardo oder Baccanti',
      ],
    },
    {
      id: 'day-6',
      date: '2026-08-01',
      weekday: 'Sa',
      label: 'Tag 6',
      route: 'Matera → Rom',
      km: 470,
      hours: 5,
      sleep: 'Rom',
      hotelId: 'hotel-rome',
      segment: 'Italien nach Bari',
      type: 'explore',
      ztlLevel: 'high',
      activities: ['Ankunft Nachmittag', 'Aperitivo, Trastevere oder Piazza Navona'],
    },
    {
      id: 'day-7',
      date: '2026-08-02',
      weekday: 'So',
      label: 'Tag 7',
      route: 'Rom',
      km: 0,
      hours: 0,
      sleep: 'Rom',
      hotelId: 'hotel-rome',
      segment: 'Italien nach Bari',
      type: 'explore',
      ztlLevel: 'high',
      activities: [
        'Vatikan + Sixtinische Kapelle (Früheintritt)',
        'Borghese-Galerie (Zeitslot)',
        'Abend Trastevere',
      ],
    },
    {
      id: 'day-8',
      date: '2026-08-03',
      weekday: 'Mo',
      label: 'Tag 8',
      route: 'Rom → Siena',
      km: 230,
      hours: 2.5,
      sleep: 'Siena',
      hotelId: 'hotel-siena',
      segment: 'Italien nach Bari',
      type: 'explore',
      ztlLevel: 'medium',
      activities: ['Piazza del Campo', 'Duomo + Piccolomini-Bibliothek', 'Osteria Le Logge'],
    },
    {
      id: 'day-9',
      date: '2026-08-04',
      weekday: 'Di',
      label: 'Tag 9',
      route: 'Siena (+ Val d\'Orcia)',
      km: 0,
      hours: 0,
      sleep: 'Siena',
      hotelId: 'hotel-siena',
      segment: 'Italien nach Bari',
      type: 'explore',
      ztlLevel: 'medium',
      activities: [
        'Pienza, Montalcino (Brunello-Verkostung)',
        'Bagno Vignoni',
      ],
    },
    {
      id: 'day-10',
      date: '2026-08-05',
      weekday: 'Mi',
      label: 'Tag 10',
      route: 'Siena → Modena (Mittag) → Bologna',
      km: 260,
      hours: 3,
      sleep: 'Bologna',
      hotelId: 'hotel-bologna',
      segment: 'Italien nach Bari',
      type: 'explore',
      ztlLevel: 'medium',
      activities: [
        'Mittagessen Modena (Franceschetta 58)',
        'Portici, Piazza Maggiore, Zwei Türme',
        'Trattoria di Via Serra',
      ],
    },
    {
      id: 'day-11',
      date: '2026-08-06',
      weekday: 'Do',
      label: 'Tag 11',
      route: 'Bologna → Stresa',
      km: 330,
      hours: 3.5,
      sleep: 'Stresa',
      hotelId: 'hotel-stresa',
      segment: 'Italien nach Bari',
      type: 'explore',
      ztlLevel: null,
      activities: ['Check-in, See, Spa', 'Villa Crespi oder Piccolo Lago'],
    },
    {
      id: 'day-12',
      date: '2026-08-07',
      weekday: 'Fr',
      label: 'Tag 12',
      route: 'Stresa',
      km: 0,
      hours: 0,
      sleep: 'Stresa',
      hotelId: 'hotel-stresa',
      segment: 'Italien nach Bari',
      type: 'chill',
      ztlLevel: null,
      activities: [
        'Borromäische Inseln (Fähre oder Privatboot)',
        'Optional: Seilbahn Monte Mottarone',
      ],
    },
    {
      id: 'day-13',
      date: '2026-08-08',
      weekday: 'Sa',
      label: 'Tag 13',
      route: 'Stresa → Simplon → Luxemburg',
      km: 720,
      hours: 7.5,
      sleep: 'Zuhause',
      hotelId: null,
      segment: 'Heimfahrt',
      type: 'drive-home',
      ztlLevel: null,
      activities: ['Abfahrt ~7:00 — Gotthard meiden'],
    },
  ],

  hotels: [
    {
      id: 'hotel-innsbruck',
      dates: ['2026-07-27'],
      checkIn: '2026-07-27',
      checkOut: '2026-07-28',
      nights: 1,
      city: 'Innsbruck',
      country: 'Österreich',
      pick: 'Hotel Penz West',
      mapsQuery: 'Hotel Penz West, Innsbruck, Austria',
      alternates: ['Holiday Inn Express (IHG)', 'Hotel Bierwirt', 'Hotel Batzenhäusl'],
      pricePerNight: 179,
      total: 179,
      reviewScore: '8.7',
      priority: 'july',
      bookBy: '2026-07-01',
      bookByLabel: 'Anfang Juli 2026',
      flags: ['parking', 'motorway'],
      notes: 'IHG Holiday Inn Express auf ih.com live prüfen (Punkte). Hötting = 5 Min. zur A12.',
      links: {
        booking:
          'https://www.booking.com/hotel/at/sporthotelpenztirol.html?checkin=2026-07-27&checkout=2026-07-28&group_adults=2&selected_currency=EUR',
        ihg: 'https://www.ihg.com',
      },
      upgrades: [],
      locked: false,
      liveSearchRequired: false,
    },
    {
      id: 'hotel-pesaro',
      dates: ['2026-07-28'],
      checkIn: '2026-07-28',
      checkOut: '2026-07-29',
      nights: 1,
      city: 'Pesaro',
      country: 'Italien',
      pick: 'Live prüfen: Lungomare (Excelsior / Baia Flaminia)',
      mapsQuery: 'Hotel Excelsior Pesaro, Lungomare',
      alternates: ['Agriturismo Ardizio 43 (Fallback ~€75)', 'Fano Lungomare'],
      pricePerNight: 100,
      total: 100,
      reviewScore: '—',
      priority: 'now',
      bookBy: '2026-07-01',
      bookByLabel: 'Anfang Juli 2026',
      flags: ['parking', 'ac', 'seafront'],
      notes: 'Booking.com: „Pesaro Lungomare“ — Hotel Excelsior, Baia Flaminia, Imperial.',
      links: {
        booking:
          'https://www.booking.com/searchresults.html?ss=Pesaro+lungomare&checkin=2026-07-28&checkout=2026-07-29&group_adults=2',
        search:
          'https://www.booking.com/searchresults.html?ss=Hotel+Excelsior+Pesaro',
      },
      upgrades: [],
      locked: false,
      liveSearchRequired: true,
      actionVerb: 'Finde dein Pesaro-Hotel am Lungomare',
      actionWhy: 'Eine Nacht am Adriatischen Meer vor der Hochzeit — die besten Strandhotels musst du live auf Booking.com wählen.',
    },
    {
      id: 'hotel-bari',
      dates: ['2026-07-29', '2026-07-30'],
      checkIn: '2026-07-29',
      checkOut: '2026-07-31',
      nights: 2,
      city: 'Bari',
      country: 'Italien',
      pick: 'Bereits gebucht (Trulli / Hochzeit)',
      mapsQuery: 'Bari, Apulien, Italien',
      alternates: [],
      pricePerNight: 0,
      total: 0,
      reviewScore: '—',
      priority: 'done',
      bookBy: null,
      bookByLabel: 'Gebucht',
      flags: [],
      notes: 'Nicht suchen — Hochzeitsunterkunft.',
      links: {},
      upgrades: [],
      locked: true,
      liveSearchRequired: false,
    },
    {
      id: 'hotel-matera',
      dates: ['2026-07-31'],
      checkIn: '2026-07-31',
      checkOut: '2026-08-01',
      nights: 1,
      city: 'Matera',
      country: 'Italien',
      pick: 'Aquatio Cave Luxury Hotel & Spa',
      mapsQuery: 'Aquatio Cave Luxury Hotel, Matera, Italy',
      alternates: ['Palazzo Viceconte', 'Sextantio Le Grotte', 'Locanda di San Martino'],
      pricePerNight: 280,
      total: 280,
      reviewScore: '4.7 TA',
      priority: 'now',
      bookBy: '2026-05-26',
      bookByLabel: 'Diese Woche',
      flags: ['parking', 'cancellation', 'cave'],
      notes: 'Storno-Politik schriftlich bestätigen. Freitag Peak — sofort buchen.',
      links: {
        booking:
          'https://www.booking.com/hotel/it/aquatio-cave-luxury-hotel-spa.html?checkin=2026-07-31&checkout=2026-08-01&group_adults=2',
      },
      upgrades: [
        { name: 'Sextantio Le Grotte', extraTotal: 90, note: '+€90 vs. Budget' },
      ],
      locked: false,
      liveSearchRequired: false,
    },
    {
      id: 'hotel-rome',
      dates: ['2026-08-01', '2026-08-02'],
      checkIn: '2026-08-01',
      checkOut: '2026-08-03',
      nights: 2,
      city: 'Rom',
      country: 'Italien',
      pick: 'Colonna Inn',
      mapsQuery: 'Colonna Inn, Roma, Italy',
      alternates: ['Crowne Plaza St. Peter\'s (IHG)', 'Catone Luxury Rooms', 'Starhotels Michelangelo'],
      pricePerNight: 166,
      total: 332,
      reviewScore: '9.3',
      priority: 'june',
      bookBy: '2026-06-15',
      bookByLabel: 'Juni 2026',
      flags: ['ztl', 'parking', 'ac'],
      notes: 'Prati außerhalb ZTL. IHG Punkte vs. Cash prüfen. AC in August-Reviews filtern.',
      links: {
        booking:
          'https://www.booking.com/hotel/it/colonna-inn-guest-house.html?checkin=2026-08-01&checkout=2026-08-03&group_adults=2&selected_currency=EUR',
        ihg: 'https://www.ihg.com/crowneplaza/hotels/gb/en/rome/romcp/hoteldetail',
      },
      upgrades: [],
      locked: false,
      liveSearchRequired: false,
      ztlHotel: true,
    },
    {
      id: 'hotel-siena',
      dates: ['2026-08-03', '2026-08-04'],
      checkIn: '2026-08-03',
      checkOut: '2026-08-05',
      nights: 2,
      city: 'Siena',
      country: 'Italien',
      pick: 'Hotel Palazzo di Valli',
      mapsQuery: 'Hotel Palazzo di Valli, Siena, Italy',
      alternates: ['Four Points Sheraton (Marriott)', 'Ca\' Bianca Relais (Pool-Splurge)'],
      pricePerNight: 158,
      total: 316,
      reviewScore: '9.4',
      priority: 'june',
      bookBy: '2026-06-15',
      bookByLabel: 'Juni 2026',
      flags: ['ztl', 'parking'],
      notes: 'Porta Romana, außerhalb ZTL. Brunello-Tasting statt Agriturismo-Splurge.',
      links: {
        booking:
          'https://www.booking.com/hotel/it/hotelpalazzodivallisiena.html?checkin=2026-08-03&checkout=2026-08-05&group_adults=2&selected_currency=EUR',
      },
      upgrades: [],
      locked: false,
      liveSearchRequired: false,
      ztlHotel: true,
    },
    {
      id: 'hotel-bologna',
      dates: ['2026-08-05'],
      checkIn: '2026-08-05',
      checkOut: '2026-08-06',
      nights: 1,
      city: 'Bologna',
      country: 'Italien',
      pick: 'Hotel Roma',
      mapsQuery: 'Hotel Roma, Bologna, Italy',
      alternates: ['Royal Hotel Carlton (ZTL-Backup)', 'Crowne Plaza De La Ville (IHG)'],
      pricePerNight: 149,
      total: 149,
      reviewScore: '8.5',
      priority: 'june',
      bookBy: '2026-06-15',
      bookByLabel: 'Juni 2026',
      flags: ['ztl', 'parking'],
      notes: 'Piazza Maggiore — ZTL-Kennzeichen schriftlich bestätigen vor Buchung.',
      links: {
        booking:
          'https://www.booking.com/hotel/it/roma-bologna.html?checkin=2026-08-05&checkout=2026-08-06&group_adults=2&selected_currency=EUR',
        ihg: 'https://www.ihg.com/crowneplaza/hotels/gb/en/bologna/bolog/hoteldetail',
      },
      upgrades: [],
      locked: false,
      liveSearchRequired: false,
      ztlHotel: true,
    },
    {
      id: 'hotel-stresa',
      dates: ['2026-08-06', '2026-08-07'],
      checkIn: '2026-08-06',
      checkOut: '2026-08-08',
      nights: 2,
      city: 'Stresa',
      country: 'Italien',
      pick: 'Hotel Regina Palace',
      mapsQuery: 'Hotel Regina Palace, Stresa, Italy',
      alternates: ['Grand Hotel des Iles Borromées', 'Villa e Palazzo Aminta'],
      pricePerNight: 285,
      total: 570,
      reviewScore: '8.6',
      priority: 'now',
      bookBy: '2026-05-26',
      bookByLabel: 'Diese Woche',
      flags: ['parking', 'spa', 'direct-booking'],
      notes: 'Direkt beim Hotel anrufen — oft €15–30/Nacht günstiger. Renovierungszimmer Seeblick anfragen.',
      links: {
        booking:
          'https://www.booking.com/hotel/it/regina-palace.html?checkin=2026-08-06&checkout=2026-08-08&group_adults=2&selected_currency=EUR',
        direct: 'https://www.reginapalace.it',
      },
      upgrades: [
        { name: 'Grand Hotel Borromées', extraTotal: 280, note: '+€280 gesamt' },
      ],
      locked: false,
      liveSearchRequired: false,
    },
  ],

  restaurants: [
    {
      id: 'rest-franceschetta',
      date: '2026-08-05',
      meal: 'Mittagessen',
      city: 'Modena',
      name: 'Franceschetta 58',
      bookWindow: '60 Tage vorher — am 06.06.2026 buchen',
      bookBy: '2026-06-06',
      priority: 'critical',
      priceEstimate: '€60–80/Person',
      optional: false,
      links: { website: 'https://www.franceschetta58.it' },
      notes: 'Kalender: 06.06.2026 sofort buchen wenn Fenster öffnet.',
      actionVerb: 'Reserviere Franceschetta 58 in Modena (Mittag 5.8.)',
      actionWhy: 'Botturas Bistro auf der Fahrt Siena–Bologna — Fenster öffnet am 06.06., danach schnell ausgebucht.',
    },
    {
      id: 'rest-giusti',
      date: '2026-08-05',
      meal: 'Mittagessen (Alt.)',
      city: 'Modena',
      name: 'Hosteria Giusti',
      bookWindow: '4 Wochen vorher',
      bookBy: '2026-07-08',
      priority: 'medium',
      priceEstimate: '€',
      optional: true,
      links: {},
      notes: '4-Tisch-Bottega, nur Mittag — E-Mail-Reservierung.',
    },
    {
      id: 'rest-francescana',
      date: null,
      meal: '—',
      city: 'Modena',
      name: 'Osteria Francescana (3⭐)',
      bookWindow: '3 Monate / Lottery',
      bookBy: null,
      priority: 'aspirational',
      priceEstimate: '€400+/Person',
      optional: true,
      links: { website: 'https://www.osteriafrancescana.it' },
      notes: 'Optional — nicht im Fortschritt gezählt.',
    },
    {
      id: 'rest-bologna-serra',
      date: '2026-08-05',
      meal: 'Abendessen',
      city: 'Bologna',
      name: 'Trattoria di Via Serra',
      bookWindow: '3 Wochen vorher',
      bookBy: '2026-07-15',
      priority: 'medium',
      priceEstimate: '€',
      optional: false,
      links: {},
      notes: 'Alternativ: All\'Osteria Bottega',
    },
    {
      id: 'rest-bologna-bottega',
      date: '2026-08-05',
      meal: 'Abendessen (Alt.)',
      city: 'Bologna',
      name: 'All\'Osteria Bottega',
      bookWindow: '3 Wochen vorher',
      bookBy: '2026-07-15',
      priority: 'medium',
      priceEstimate: '€',
      optional: true,
      links: {},
      notes: '',
    },
    {
      id: 'rest-villa-crespi',
      date: '2026-08-06',
      meal: 'Abendessen',
      city: 'Lake Orta (von Stresa)',
      name: 'Villa Crespi (2⭐ Cannavacciuolo)',
      bookWindow: '6–8 Wochen — jetzt',
      bookBy: '2026-05-26',
      priority: 'critical',
      priceEstimate: '€',
      optional: false,
      links: { website: 'https://www.villacrespi.it' },
      notes: '40 Min. von Stresa — Finale-Highlight.',
    },
    {
      id: 'rest-piccolo-lago',
      date: '2026-08-06',
      meal: 'Abendessen (Alt.)',
      city: 'Mergozzo',
      name: 'Piccolo Lago (1⭐)',
      bookWindow: '3–4 Wochen',
      bookBy: '2026-07-15',
      priority: 'medium',
      priceEstimate: '~€140/Person',
      optional: true,
      links: {},
      notes: 'Leichter, seenah.',
    },
    {
      id: 'rest-pipero',
      date: '2026-08-01',
      meal: 'Abendessen',
      city: 'Rom',
      name: 'Pipero (1⭐)',
      bookWindow: '3–4 Wochen',
      bookBy: '2026-07-10',
      priority: 'medium',
      priceEstimate: '€',
      optional: false,
      links: {},
      notes: 'Alternativ: Roscioli (Carbonara-Kult).',
    },
    {
      id: 'rest-roscioli',
      date: '2026-08-02',
      meal: 'Abendessen (Alt.)',
      city: 'Rom',
      name: 'Roscioli',
      bookWindow: '3–4 Wochen',
      bookBy: '2026-07-10',
      priority: 'medium',
      priceEstimate: '€',
      optional: true,
      links: {},
      notes: 'Mittag teils spontan möglich.',
    },
    {
      id: 'rest-le-logge',
      date: '2026-08-03',
      meal: 'Abendessen',
      city: 'Siena',
      name: 'Osteria Le Logge',
      bookWindow: '2–3 Wochen',
      bookBy: '2026-07-15',
      priority: 'medium',
      priceEstimate: '€',
      optional: false,
      links: {},
      notes: 'Alternativ: Arnolfo (2⭐, Colle Val d\'Elsa).',
    },
    {
      id: 'rest-arnolfo',
      date: '2026-08-04',
      meal: 'Abendessen (Alt.)',
      city: 'Colle Val d\'Elsa',
      name: 'Arnolfo (2⭐)',
      bookWindow: '2–3 Wochen',
      bookBy: '2026-07-15',
      priority: 'low',
      priceEstimate: '€',
      optional: true,
      links: {},
      notes: '25 Min. von Siena.',
    },
  ],

  sights: [
    {
      id: 'sight-vatican',
      date: '2026-08-02',
      city: 'Rom',
      name: 'Vatikanmuseen + Sixtinische Kapelle',
      bookWindow: '~30 Tage — Früheintritt empfohlen',
      bookBy: '2026-07-03',
      priority: 'medium',
      link: 'https://www.museivaticani.va',
      notes: 'Frühstücks-/Früheintritt-Slot für weniger Menschenmassen.',
    },
    {
      id: 'sight-borghese',
      date: '2026-08-02',
      city: 'Rom',
      name: 'Borghese-Galerie',
      bookWindow: '2–3 Wochen — Pflicht',
      bookBy: '2026-07-10',
      priority: 'high',
      link: 'https://galleriaborghese.beniculturali.it',
      notes: 'Zeitslot — ausverkauft schnell.',
    },
    {
      id: 'sight-colosseum',
      date: '2026-08-03',
      city: 'Rom',
      name: 'Kolosseum + Forum + Palatin (morgens)',
      bookWindow: '1+ Woche',
      bookBy: '2026-07-25',
      priority: 'medium',
      link: 'https://colosseo.it',
      notes: 'Arena-Boden-Upgrade wenn verfügbar. Abfahrt Siena ~11:00.',
    },
    {
      id: 'sight-matera-guide',
      date: '2026-07-31',
      city: 'Matera',
      name: 'Private Sassi-Führung',
      bookWindow: '1–2 Wochen',
      bookBy: '2026-07-20',
      priority: 'medium',
      link: 'https://www.sassiweb.it',
      notes: 'Ohne Guide nur Steine — mit Guide unvergesslich.',
    },
    {
      id: 'sight-brunello',
      date: '2026-08-04',
      city: 'Montalcino',
      name: 'Brunello-Verkostung (Banfi / Argiano)',
      bookWindow: '2 Wochen',
      bookBy: '2026-07-20',
      priority: 'medium',
      link: 'https://www.castelbanfi.com',
      notes: 'Val-d\'Orcia-Tag von Siena.',
    },
    {
      id: 'sight-borromean',
      date: '2026-08-07',
      city: 'Stresa',
      name: 'Borromäische Inseln (Fähre oder Privatboot)',
      bookWindow: 'Fähre spontan; Privatboot 2 Wochen',
      bookBy: '2026-07-24',
      priority: 'low',
      link: 'https://www.navlaghi.it',
      notes: 'Privatboot Sonnenuntergang ~€250–400.',
    },
    {
      id: 'sight-mottarone',
      date: '2026-08-07',
      city: 'Stresa',
      name: 'Seilbahn Monte Mottarone',
      bookWindow: '1 Woche oder vor Ort',
      bookBy: '2026-07-31',
      priority: 'low',
      link: 'https://www.mottarone.it',
      notes: 'Optional — 7-Seen-Panorama.',
    },
    {
      id: 'sight-stresa-spa',
      date: '2026-08-06',
      city: 'Stresa',
      name: 'Spa Borromées (auch für Nicht-Gäste)',
      bookWindow: '2 Wochen',
      bookBy: '2026-07-20',
      priority: 'low',
      link: 'https://www.borromees.com',
      notes: 'Wenn nicht im Borromées übernachtet.',
    },
  ],

  cleanupTasks: [
    {
      id: 'cleanup-pesaro',
      text: 'Pesaro: Booking.com „Lungomare“ — Excelsior, Baia Flaminia, Imperial (€90–130, Parkplatz, Meerblick)',
    },
    {
      id: 'cleanup-ihg',
      text: 'IHG live: Innsbruck (HIE), Rom (Crowne Plaza St. Peter\'s), Bologna (Crowne Plaza De La Ville)',
    },
    {
      id: 'cleanup-bologna-ztl',
      text: 'Hotel Roma Bologna: ZTL-Kennzeichen schriftlich bestätigen — sonst Royal Hotel Carlton',
    },
    {
      id: 'cleanup-matera-cancel',
      text: 'Aquatio Matera: Storno-Politik schriftlich (Peak-Sommer oft 30 Tage strikt)',
    },
    {
      id: 'cleanup-stresa-direct',
      text: 'Stresa: Regina Palace / Borromées direkt anrufen — Best Rate inkl. Frühstück 6.–7.8.',
    },
    {
      id: 'cleanup-rome-ac',
      text: 'Colonna Inn: August-Reviews 2024/25 auf AC prüfen',
    },
  ],

  driverSections: [
    {
      id: 'driver-docs',
      title: 'Dokumente & Rechtliches',
      items: [
        'Führerschein + optionaler internationaler Führerschein (Commune)',
        'Fahrzeugschein + Grüne Versicherungskarte',
        'Reisepässe / Ausweise beider Reisenden',
        'Pannenhilfe EU: Versicherung für IT, CH, AT prüfen',
      ],
    },
    {
      id: 'driver-tolls',
      title: 'Vignetten & Maut',
      items: [
        'Österreich: Digitale Vignette 10 Tage ~€12,40 vor Grenze',
        'Brenner A13: ~€11 pro Richtung (separat von Vignette)',
        'Italien Autostrada: ~€50 Hinweg Brenner–Bari, ~€40 Rückweg Bari–Stresa — gelbe „Carte“-Spur',
        'Schweiz: Jahresvignette ~€40 (Simplon-Rückweg)',
        'Kein Mont-Blanc / Fréjus auf dieser Route',
      ],
    },
    {
      id: 'driver-ztl',
      title: 'ZTL-Regeln (Italien)',
      items: [
        'Rom: Historisches Zentrum — Hotel außerhalb ZTL oder Kennzeichen-Registrierung',
        'Siena: Kern hinter Mauern ZTL — außerhalb übernachten, zu Fuß rein',
        'Bologna: ZTL — Hotel mit Garage muss Kennzeichen registrieren',
        'Matera: Sassi fußläufig — Parken obere Stadt laut Hotel',
        'Modena (5.8. Mittag): Parcheggio Novi Sad oder Roma',
        'GPS in engen Gassen nicht blind vertrauen — roter Kreis „ZTL“',
      ],
    },
    {
      id: 'driver-fuel',
      title: 'Tanken & Zahlung',
      items: [
        'Vor Autobahn-Auffahrt tanken (Autobahn ~10–15% teurer)',
        '€100–150 Bargeld für kleine Trattorien / Agriturismi',
        'Revolut + Backup Visa/Mastercard — Amex lückenhaft',
        'Benzina (grün) vs. Gasolio/Diesel (schwarz/gelb) — nicht verwechseln',
      ],
    },
    {
      id: 'driver-summer',
      title: 'Sommer & August',
      items: [
        '8.8. Abfahrt Stresa ~7:00 — Wochenendverkehr CH meiden',
        'Rom/Süd: 35–38°C — AC im Auto testen, Hut, Sonnencreme, 3L Wasser/Tag',
        'Restaurant-Buchungen vor Mai: im August Anruf zur Bestätigung (Ferie)',
        'Ferragosto 15.8.: irrelevant (daheim)',
      ],
    },
    {
      id: 'driver-prep',
      title: 'Woche vor Abfahrt',
      items: [
        'Reifen, Öl, Kühlmittel, Wischer, Bremsen',
        'Warndreieck, Warnweste pro Insasse, Erste-Hilfe-Set',
        'Handyhalterung, Ladekabel, optional Dashcam',
        'Offline-Karten: Italien, Österreich, Schweiz',
        'Free Now / IT Taxi für Rom',
      ],
    },
  ],

  ztlEmailTemplates: [
    {
      hotelId: 'hotel-bologna',
      hotelName: 'Hotel Roma, Bologna',
      arrivalDate: '2026-08-05',
      subjectDe: 'Anreise mit Auto — ZTL-Kennzeichen 5. August',
      bodyDe:
        'Guten Tag,\n\nwir reisen am 5. August 2026 abends mit dem Auto an (2 Erwachsene, ein Fahrzeug). Können Sie unser Kennzeichen bei der Gemeinde Bologna für die ZTL zur An- und Abreise registrieren?\n\nBitte bestätigen Sie schriftlich, dass dies für Ihre Gäste mit Parkplatz/Valet funktioniert.\n\nVielen Dank,\n[Name]',
      bodyIt:
        'Buongiorno,\n\narriviamo in auto la sera del 5 agosto 2026 (2 adulti, un veicolo). Potete registrare la nostra targa presso il Comune di Bologna per la ZTL in arrivo e partenza?\n\nVi prego di confermare per iscritto che questo servizio è incluso per gli ospiti con parcheggio/valet.\n\nGrazie,\n[Nome]',
    },
    {
      hotelId: 'hotel-rome',
      hotelName: 'Colonna Inn, Rom',
      arrivalDate: '2026-08-01',
      subjectDe: 'Anreise mit Auto — ZTL 1.–3. August',
      bodyDe:
        'Guten Tag,\n\nwir reisen am 1. August 2026 mit dem Auto an und bleiben zwei Nächte (Abreise 3. August). Registrieren Sie das Kennzeichen für die römische ZTL bei An- und Abreise?\n\nUnser Fahrzeug: [Kennzeichen]. Bitte kurze schriftliche Bestätigung.\n\nVielen Dank,\n[Name]',
      bodyIt:
        'Buongiorno,\n\narriviamo in auto il 1 agosto 2026 e partiamo il 3 agosto (2 notti). Registrate la targa per la ZTL di Roma in arrivo e partenza?\n\nTarga: [targa]. Conferma scritta, per favore.\n\nGrazie,\n[Nome]',
    },
    {
      hotelId: 'hotel-siena',
      hotelName: 'Hotel Palazzo di Valli, Siena',
      arrivalDate: '2026-08-03',
      subjectDe: 'Anreise mit Auto — Parken & ZTL 3.–5. August',
      bodyDe:
        'Guten Tag,\n\nwir reisen am 3. August 2026 mit dem Auto an (2 Erwachsene). Ist Parken auf dem Gelände inklusive? Gibt es ZTL-Registrierung oder reichen wir nur über Ihren Parkplatz ein?\n\nBitte kurze Bestätigung.\n\nVielen Dank,\n[Name]',
      bodyIt:
        'Buongiorno,\n\narriviamo in auto il 3 agosto 2026 (2 adulti). Il parcheggio in loco è incluso? È necessaria registrazione ZTL o basta il vostro parcheggio?\n\nGrazie per una breve conferma.\n\n[Nome]',
    },
  ],

  bookingPriorityOrder: [
    'hotel-matera',
    'hotel-stresa',
    'rest-villa-crespi',
    'rest-franceschetta',
    'hotel-rome',
    'hotel-siena',
    'hotel-bologna',
    'hotel-innsbruck',
    'hotel-pesaro',
  ],

  budgetScenarios: [
    { label: 'Deine Picks', total: 1926, delta: -14 },
    { label: '+ Borromées Stresa', total: 2206, delta: 266 },
    { label: '+ Sextantio Matera', total: 2016, delta: 90 },
    { label: '+ Beide Upgrades', total: 2296, delta: 356 },
  ],
};

if (typeof window !== 'undefined') {
  window.TRIP_DATA = TRIP_DATA;
}
