/** @typedef {'pick'|'alternate'|'upgrade'|'inspiration'|'search'} OptionRole */

/**
 * Showcase data — hotels with choices, map stops, dining (from trip plan).
 * @type {typeof window.SHOWCASE_DATA}
 */
window.SHOWCASE_DATA = {
  meta: {
    hotelBudget: 1940,
    hotelPlanned: 1926,
    restaurants: { min: 300, max: 500 },
    tolls: { min: 110, max: 150 },
    fuel: { min: 200, max: 280 },
    totalKm: 4155,
  },

  routeStops: [
    { id: 'lux', label: 'Luxemburg', segment: 'start', lat: 49.6116, lng: 6.1319 },
    { id: 'innsbruck', label: 'Innsbruck', dayId: 'day-1', segment: 'outbound', lat: 47.2692, lng: 11.4041 },
    { id: 'pesaro', label: 'Pesaro', dayId: 'day-2', segment: 'outbound', lat: 43.9097, lng: 12.9133 },
    { id: 'bari', label: 'Bari', dayId: 'day-3', segment: 'wedding', lat: 41.1171, lng: 16.8719 },
    { id: 'matera', label: 'Matera', dayId: 'day-5', segment: 'italy', lat: 40.6664, lng: 16.6043 },
    { id: 'rome', label: 'Rom', dayId: 'day-6', segment: 'italy', lat: 41.9028, lng: 12.4964 },
    { id: 'siena', label: 'Siena', dayId: 'day-8', segment: 'italy', lat: 43.3188, lng: 11.3308 },
    { id: 'bologna', label: 'Bologna', dayId: 'day-10', segment: 'italy', lat: 44.4949, lng: 11.3426 },
    { id: 'stresa', label: 'Stresa', dayId: 'day-11', segment: 'italy', lat: 45.8842, lng: 8.5298 },
    { id: 'lux-end', label: 'Luxemburg', segment: 'return', lat: 49.6116, lng: 6.1319 },
  ],

  segmentColors: {
    outbound: '#b85c38',
    wedding: '#c9a227',
    italy: '#4a6741',
    return: '#7a6f5a',
  },

  hotelStops: [
    {
      id: 'innsbruck',
      city: 'Innsbruck',
      country: 'Österreich',
      dates: '27. Juli · 1 Nacht',
      bookBy: 'Anfang Juli 2026',
      status: 'choose',
      notes: 'Nach der langen Fahrt: Parkplatz & schnell zur A12. IHG-Punkte für Holiday Inn prüfen.',
      options: [
        {
          role: 'pick',
          name: 'Hotel Penz West',
          priceNight: 179,
          total: 179,
          score: '8.7',
          image: 'hotels/hotel-innsbruck.jpg',
          tags: ['Parkplatz', 'Autobahn'],
          booking: 'https://www.booking.com/hotel/at/sporthotelpenztirol.html?checkin=2026-07-27&checkout=2026-07-28&group_adults=2',
          maps: 'Hotel Penz West, Innsbruck, Austria',
        },
        {
          role: 'alternate',
          name: 'Holiday Inn Express (IHG)',
          priceNight: null,
          note: 'Punkte / Cash auf ih.com',
          maps: 'Holiday Inn Express Innsbruck',
        },
        { role: 'alternate', name: 'Hotel Bierwirt', maps: 'Hotel Bierwirt Innsbruck' },
        { role: 'alternate', name: 'Hotel Batzenhäusl', maps: 'Hotel Batzenhäusl Innsbruck' },
      ],
    },
    {
      id: 'pesaro',
      city: 'Pesaro',
      country: 'Italien',
      dates: '28. Juli · 1 Nacht',
      bookBy: 'Anfang Juli 2026',
      status: 'search',
      notes: 'Am Lungomare buchen — Sonnenuntergang & Fisch am Strand.',
      options: [
        {
          role: 'pick',
          name: 'Hotel Excelsior',
          priceNight: '~100',
          image: 'hotels/hotel-pesaro.jpg',
          tags: ['Meer', 'Lungomare'],
          booking: 'https://www.booking.com/searchresults.html?ss=Hotel+Excelsior+Pesaro&checkin=2026-07-28&checkout=2026-07-29&group_adults=2',
          maps: 'Hotel Excelsior Pesaro Lungomare',
        },
        {
          role: 'alternate',
          name: 'Baia Flaminia Resort',
          booking: 'https://www.booking.com/searchresults.html?ss=Baia+Flaminia+Pesaro&checkin=2026-07-28&checkout=2026-07-29&group_adults=2',
          maps: 'Baia Flaminia Pesaro',
        },
        {
          role: 'alternate',
          name: 'Hotel Imperial',
          maps: 'Hotel Imperial Pesaro',
        },
        {
          role: 'alternate',
          name: 'Agriturismo Ardizio 43',
          priceNight: '~75',
          note: 'Günstiger Fallback',
          maps: 'Agriturismo Ardizio Pesaro',
        },
      ],
    },
    {
      id: 'bari',
      city: 'Bari / Alberobello',
      country: 'Italien',
      dates: '29.–31. Juli · 2 Nächte',
      status: 'booked',
      notes: 'Hochzeitsunterkunft ist fix — unten nur zur Inspiration (Trulli-Vibe).',
      options: [
        {
          role: 'pick',
          name: 'Eure Trulli (gebucht)',
          note: 'Nicht neu suchen — Hochzeit',
          image: 'hotels/hotel-bari-trulli.jpg',
          maps: 'Bari, Apulien, Italien',
        },
        {
          role: 'inspiration',
          name: 'Le Alcove · Alberobello',
          score: '5★ · Trulli-Suites',
          note: 'Ca. 55 km von Bari — so ähnlich könnte es aussehen',
          image: 'hotels/hotel-bari-trulli.jpg',
          booking: 'https://lealcove.it/en',
          maps: 'Le Alcove, Piazza Ferdinando IV, Alberobello',
        },
        {
          role: 'inspiration',
          name: 'Trulli Anti Charme Resort',
          maps: 'Trulli Anti Charme Alberobello',
          booking: 'https://www.booking.com/searchresults.html?ss=trulli+alberobello+luxury',
        },
      ],
    },
    {
      id: 'matera',
      city: 'Matera',
      country: 'Italien',
      dates: '31. Juli – 1. Aug. · 1 Nacht',
      bookBy: 'Diese Woche',
      status: 'urgent',
      notes: 'Freitag Peak — Storno schriftlich bestätigen lassen.',
      options: [
        {
          role: 'pick',
          name: 'Aquatio Cave Luxury Hotel & Spa',
          priceNight: 280,
          total: 280,
          score: '4.7 TA',
          image: 'hotels/hotel-matera.jpg',
          tags: ['Sassi', 'Spa', 'Storno prüfen'],
          booking: 'https://www.booking.com/hotel/it/aquatio-cave-luxury-hotel-spa.html?checkin=2026-07-31&checkout=2026-08-01&group_adults=2',
          maps: 'Aquatio Cave Luxury Hotel, Matera',
        },
        {
          role: 'upgrade',
          name: 'Sextantio Le Grotte',
          note: '+€90 vs. Budget',
          maps: 'Sextantio Le Grotte della Civita Matera',
        },
        { role: 'alternate', name: 'Palazzo Viceconte', maps: 'Palazzo Viceconte Matera' },
        { role: 'alternate', name: 'Locanda di San Martino', maps: 'Locanda di San Martino Matera' },
      ],
    },
    {
      id: 'rome',
      city: 'Rom',
      country: 'Italien',
      dates: '1.–3. Aug. · 2 Nächte',
      bookBy: 'Juni 2026',
      status: 'choose',
      notes: 'Prati = außerhalb strengster ZTL. AC in Bewertungen filtern (August!).',
      options: [
        {
          role: 'pick',
          name: 'Colonna Inn',
          priceNight: 166,
          total: 332,
          score: '9.3',
          image: 'hotels/hotel-rome.jpg',
          tags: ['ZTL-Hilfe', 'Prati', 'Vatikan'],
          booking: 'https://www.booking.com/hotel/it/colonna-inn-guest-house.html?checkin=2026-08-01&checkout=2026-08-03&group_adults=2',
          maps: 'Colonna Inn, Roma, Italy',
        },
        {
          role: 'alternate',
          name: "Crowne Plaza St. Peter's (IHG)",
          booking: 'https://www.ihg.com/crowneplaza/hotels/gb/en/rome/romcp/hoteldetail',
          maps: "Crowne Plaza Rome St Peter's",
        },
        { role: 'alternate', name: 'Catone Luxury Rooms', maps: 'Catone Luxury Rooms Rome' },
        { role: 'alternate', name: 'Starhotels Michelangelo', maps: 'Starhotels Michelangelo Rome' },
      ],
    },
    {
      id: 'siena',
      city: 'Siena',
      country: 'Italien',
      dates: '3.–5. Aug. · 2 Nächte',
      bookBy: 'Juni 2026',
      status: 'choose',
      notes: 'Porta Romana, außerhalb ZTL — Basis für Val-d\'Orcia-Ausflüge.',
      options: [
        {
          role: 'pick',
          name: 'Hotel Palazzo di Valli',
          priceNight: 158,
          total: 316,
          score: '9.4',
          image: 'hotels/hotel-siena.jpg',
          tags: ['Parkplatz', 'ZTL außen'],
          booking: 'https://www.booking.com/hotel/it/hotelpalazzodivallisiena.html?checkin=2026-08-03&checkout=2026-08-05&group_adults=2',
          maps: 'Hotel Palazzo di Valli, Siena',
        },
        {
          role: 'alternate',
          name: 'Four Points Sheraton (Marriott)',
          maps: 'Four Points Sheraton Siena',
        },
        {
          role: 'alternate',
          name: "Ca' Bianca Relais",
          note: 'Pool-Splurge',
          maps: "Ca' Bianca Relais Tuscany",
        },
      ],
    },
    {
      id: 'bologna',
      city: 'Bologna',
      country: 'Italien',
      dates: '5. Aug. · 1 Nacht',
      bookBy: 'Juni 2026',
      status: 'choose',
      notes: 'ZTL-Kennzeichen schriftlich bestätigen vor Buchung.',
      options: [
        {
          role: 'pick',
          name: 'Hotel Roma',
          priceNight: 149,
          total: 149,
          score: '8.5',
          image: 'hotels/hotel-bologna.jpg',
          tags: ['Piazza Maggiore', 'ZTL'],
          booking: 'https://www.booking.com/hotel/it/roma-bologna.html?checkin=2026-08-05&checkout=2026-08-06&group_adults=2',
          maps: 'Hotel Roma, Bologna',
        },
        {
          role: 'alternate',
          name: 'Royal Hotel Carlton',
          note: 'ZTL-Backup',
          maps: 'Royal Hotel Carlton Bologna',
        },
        {
          role: 'alternate',
          name: 'Crowne Plaza De La Ville (IHG)',
          booking: 'https://www.ihg.com/crowneplaza/hotels/gb/en/bologna/bolog/hoteldetail',
          maps: 'Crowne Plaza Bologna',
        },
      ],
    },
    {
      id: 'stresa',
      city: 'Stresa',
      country: 'Italien',
      dates: '6.–8. Aug. · 2 Nächte',
      bookBy: 'Diese Woche',
      status: 'urgent',
      notes: 'Direkt anrufen — oft günstiger. Zimmer mit Seeblick nach Renovierung anfragen.',
      options: [
        {
          role: 'pick',
          name: 'Hotel Regina Palace',
          priceNight: 285,
          total: 570,
          score: '8.6',
          image: 'hotels/hotel-stresa.jpg',
          tags: ['See', 'Spa', 'Direktbuchung'],
          booking: 'https://www.booking.com/hotel/it/regina-palace.html?checkin=2026-08-06&checkout=2026-08-08&group_adults=2',
          direct: 'https://www.reginapalace.it',
          maps: 'Hotel Regina Palace, Stresa',
        },
        {
          role: 'upgrade',
          name: 'Grand Hotel des Iles Borromées',
          note: '+€280 gesamt',
          maps: 'Grand Hotel Borromees Stresa',
        },
        {
          role: 'alternate',
          name: 'Villa e Palazzo Aminta',
          maps: 'Villa e Palazzo Aminta Stresa',
        },
      ],
    },
  ],

  dining: [
    {
      date: '5. Aug.',
      city: 'Modena',
      meal: 'Mittag',
      pick: 'Franceschetta 58',
      alt: 'Hosteria Giusti',
      bookBy: '06.06.2026',
      priority: 'critical',
      website: 'https://www.franceschetta58.it',
    },
    {
      date: '5. Aug.',
      city: 'Bologna',
      meal: 'Abend',
      pick: 'Trattoria di Via Serra',
      alt: "All'Osteria Bottega",
      bookBy: '15.07.2026',
    },
    {
      date: '3. Aug.',
      city: 'Siena',
      meal: 'Abend',
      pick: 'Osteria Le Logge',
      alt: 'Arnolfo (2⭐)',
      bookBy: '15.07.2026',
    },
    {
      date: '1.–2. Aug.',
      city: 'Rom',
      meal: 'Abend',
      pick: 'Pipero (1⭐)',
      alt: 'Roscioli',
      bookBy: '10.07.2026',
    },
    {
      date: '6. Aug.',
      city: 'Stresa / Orta',
      meal: 'Abend',
      pick: 'Villa Crespi (2⭐)',
      alt: 'Piccolo Lago',
      bookBy: 'Diese Woche',
      priority: 'critical',
      website: 'https://www.villacrespi.it',
    },
  ],
};
